theme: jekyll-theme-minimal
title: Ohmyfood homepage
description: Third project of the "Web Developer" course at OpenClassroom. The objective is to integrate and dynamize a web page with CSS animations using the Sass preprocessor. Bookmark this to keep an eye on my project updates!
